# fly.toml app configuration file generated for hng-week-one-25 on 2025-10-20T05:19:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hng-week-one-25'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
